### ISSUE TITLE
Terminal has echo off when exiting from an exception.

### ISSUE THREAD

**Issue by regebro** [wardi/urwid#126]
The terminal has echo off everytime the program exits because of an exception (Except ExitMailLoop). This means I have to type "reset" all the time, and it's extremely annoying. Workarounds appreciated.

**Comment by regebro** [comment]
I made a workaround like this:

    class MainLoop(urwid.MainLoop):
        def run(self):
            try:
                self._run()
            except urwid.ExitMainLoop:
                pass
            except Exception:
                self.screen.stop()
                raise

I think this probably is how urwid.ExitMainLoop.run() should look. I did see a documentation claiming that this is what it does, but it doesn't.

**Comment by ngzhian** [comment]
@regebro :+1:  for this issue. I have a habit of using `Ctrl+C` to exit my programs, this causes the same issue as well! Do you want to work on a PR for this, I think @wardi may appreciate that. Else I have some time to just spin up a PR based on the code you've already written.

**Comment by wardi** [comment]
reported fixed by #149
