### ISSUE TITLE
Issues with urwid.ExitMainLoop()

### ISSUE THREAD

**Issue by winbornejw** [wardi/urwid#127]
When exiting the main loop with the latest version available in pip, raising ExitMainLoop doesn't look to be existing cleanly or completely until the entire script is closed. I noticed this because my tool is designed to run bash commands after urwid's work is done. I removed as much as possible to show the issue here. This is urwid 1.3.0

    import urwid
    import os
    
    
    class TicketLoginUI(urwid.WidgetPlaceholder):
        def __init__(self):
            self.LastTicketNumber = None
            self.menu()
    
        def menu(self):
            choices = u'Chapman Cleese Gilliam Idle Jones Palin'.split()
    
            footer = urwid.Columns([
                (9, urwid.Button('Close', on_press=self.ChooseTicket, user_data=None)),
            ])
    
            choicelist = []
            for choice in choices:
                button = urwid.Columns([
                    (24, urwid.LineBox(urwid.Button(choice, self.ChooseTicket, choice))),
                ])
                choicelist.append(urwid.AttrMap(button, None, focus_map='reversed'))
    
            linebox = urwid.LineBox(urwid.ListBox(urwid.SimpleFocusListWalker(choicelist)))
    
            body = [('weight', 1, linebox), ('pack', footer)]
    
            self.original_widget = urwid.Pile(body)
    
        def ChooseTicket(self, button, ticketnumber=None):
            self.LastTicketNumber = ticketnumber
            raise urwid.ExitMainLoop()
    
    
    ticketloginui = TicketLoginUI()
    urwid.MainLoop(ticketloginui, palette=[('reversed', 'standout', '')]).run()
    if ticketloginui.LastTicketNumber:
        command = "echo 'You chose {choice}.'; sleep 10".format(choice=ticketloginui.LastTicketNumber)
        os.system(command)

**Comment by winbornejw** [comment]
I did some more poking and found that this is also an issue in 1.2.2 but not 1.1.3.

**Comment by winbornejw** [comment]
Been installing many versions of urwid and problem seems to have started between 1.2.0 and 1.2.1.
1.2.0 works fine and 1.2.1 has the issue.

**Comment by wardi** [comment]
is it broken on master? Are you using git bisect to find out when it broke?

**Comment by winbornejw** [comment]
It is giving the issue with master as well and I was building specific commits using pip to test them. Can't say I'm familiar with git bisect.

**Comment by wardi** [comment]
@winbornejw look it up, you'll love it for this sort of thing!

Just `git clone` this repo, run `setup.py develop` to install urwid from the git clone then use `git bisect` to tell you which commit caused the breakage. All you have to do is tell it `git bisect good` or `git bisect bad` and git will move to the next commit to test. With setup.py develop you don't need to reinstall urwid every step, you'll just be using the version from that directory.

**Comment by winbornejw** [comment]
Still vague on `git bisect` and its not helping that I'm working in a virtual machine at the moment, but I did find that it was caused by 65c8722b740970bb0c944dfe4092010ed507aa58. Added the newline back in my local install and that does correct it. Will continue poking at it.

**Comment by winbornejw** [comment]
Looks like a return instead of newline will give the terminal a reason to update without giving a newline, making #60 and this issue both happy. Here's exactly what is working for me in urwid/raw_display.py
```python
self._term_output_file.write(
    self._attrspec_to_escape(AttrSpec('',''))
    + escape.SI
    + move_cursor
    + escape.SHOW_CURSOR
    + "\r")
```

**Comment by wardi** [comment]
@winbornejw that's great work! do want to send a pull request? I can put out a release with thins fix
