### ISSUE TITLE
Setting focus of ListBoxes manually fails to redraw

### ISSUE THREAD

**Issue by Kwpolska** [wardi/urwid#131]
I tried to implement Home/End keys in my ListBox.  I tried to do it naïvely, via the unhandled input function:

```py
self.box = urwid.ListBox(…)

def _unhandled(self, key):
    if key == 'home':
        self.box.set_focus(0)
```

The focused widget changes (pressing ↓ gets you the second list entry from top), but the list appearance does not reflect that.  How can I get it to redraw?

**Comment by hkoof** [comment]
This way it works:
```python
import urwid

class MyListBox(urwid.ListBox):
    def keypress(self, size, key):
        if key == 'home':
            self.set_focus(0)
        elif key == 'end':
            self.set_focus(len(self.body) - 1)

        super(MyListBox, self).keypress(size, key)

listwalker = urwid.SimpleFocusListWalker(list())
for i in range(100):
    listwalker.append(urwid.Button(str(i)))
   
box = MyListBox(listwalker)
loop = urwid.MainLoop(box) 
loop.run()
```

**Comment by Kwpolska** [comment]
Thanks! I had to add a `return` before the `super` line to keep the unhandled input handler working (I use it for global keybindings).

I’m a new urwid user, and I love urwid’s simple and friendly APIs.  I appreciate everyone’s hard work on the project!

**Comment by hkoof** [comment]
Yes, I did forget proper returns... Fixed the example now. Thanks!
