### ISSUE TITLE
Is it possible to open another program then go back?

### ISSUE THREAD

**Issue by laike9m** [wardi/urwid#133]
Basically I want to know if it's possible to open vim to edit some file then exit vim and let urwid loop continue. If it's not possible, I have to edit text using urwid, which is much more complicated. Thx.

**Comment by wardi** [comment]
Sure, just call [mainloop.screen.stop()](http://urwid.org/reference/display_modules.html#urwid.web_display.Screen.stop) before starting vim, then [mainloop.screen.start()](http://urwid.org/reference/display_modules.html#urwid.web_display.Screen.start) when returning to your application.

**Comment by laike9m** [comment]
Thx wardi, but it doesn't seem to work:

```
def run_task(button):
    status = urwid.Text(u'running...')
    main.original_widget = urwid.Filler(status)
    e = ThreadPoolExecutor(max_workers=1)
    m.screen.stop()
    f = e.submit(subprocess.Popen, ['vim test'], shell=True)
    f.add_done_callback(callback)


def callback(future):
    m.screen.start()
```

What have I done wrong?

**Comment by wardi** [comment]
oh, you want to keep the main loop running while vim is running? Why not skip the threads and just block until vim is done?

I'm pretty sure running the main loop while the screen is stopped is untested. Would be nice if that worked by just returning no input and not updating any screen. If you really need that consider contributing fixes to urwid to make it work.

**Comment by laike9m** [comment]
Thank you very much! It works! This is what I've got:
```
def run_task(button):
    status = urwid.Text(u'running...')
    main.original_widget = urwid.Filler(status)
    m.screen.stop()
    subprocess.call(['vim ./test'], shell=True)
    m.screen.start()
```
