### ISSUE TITLE
python3.2 build fails due to unicode literals in twisted dependency

### ISSUE THREAD

**Issue by douglas-larocca** [wardi/urwid#139]
This only affects python3.2. [PEP 414](https://www.python.org/dev/peps/pep-0414/) brought unicode literals back for >=3.3. It appears twisted developers are targeting 3.3 for their python3 port.

**Comment by wardi** [comment]
Yeah, this used to be working, so we could pin an earlier twisted release for the Python 3.2 tests or strip twisted out of the tests for Python 3.2

**Comment by douglas-larocca** [comment]
Sounds good, I'll close the issue.

**Comment by wardi** [comment]
Let's leave this open 'till we fix it

**Comment by wardi** [comment]
Fixed now
