### ISSUE TITLE
Problem over windows platform

### ISSUE THREAD

**Issue by vit1251** [wardi/urwid#152]
Hi, please create on main readme file requirement to environment try to use on windows platform and have error:

```bash
Traceback (most recent call last):
  File "01_urwid_text.py", line 5, in <module>
    loop = urwid.MainLoop(fill)
  File "C:\Python27\lib\site-packages\urwid\main_loop.py", line 111, in __init__
    screen = raw_display.Screen()
  File "C:\Python27\lib\site-packages\urwid\raw_display.py", line 89, in __init__
    fcntl.fcntl(self._resize_pipe_rd, fcntl.F_SETFL, os.O_NONBLOCK)
NameError: global name 'fcntl' is not defined
```

Do you support WIndows platform?

**Comment by Xkonti** [comment]
I have the same problem. I am using Python 3.5 32 bit on windows 10. My code is just first tutorial.
![urwid](https://cloud.githubusercontent.com/assets/5722272/10418279/16afa0f4-7057-11e5-860c-c88d9faa4572.png)

**Comment by makarchuk** [comment]
I suppose it's not supported because of this(http://stackoverflow.com/a/1422436)

Urwid relies on this lib and it's not working under windows

**Comment by wardi** [comment]
Urwid doesn't have windows support at the moment. Maybe consider python prompt toolkit instead?

**Comment by wardi** [comment]
I've used Urwid in Windows with cygwin in the past. There's also a curses implementation for windows somewhere that might work with curses_display. You should also be able to run an urwid application with twisted as an ssh server that renders via the ssh connections on windows (with putty or other real unix terminals connecting to it)

There's no reason to prevent those cases if someone wants to use them right now.

**Comment by yhh2021** [comment]
> Urwid doesn't have windows support at the moment. Maybe consider python prompt toolkit instead?

Thanks for pointing this out! For later readers I suggest [asciimatics](https://github.com/peterbrittain/asciimatics), which runs on both Windows and the Unix-family systems
