### ISSUE TITLE
Urwid examples web page- out of date?

### ISSUE THREAD

**Issue by ReddyKilowatt** [wardi/urwid#156]
After installing Urwid 1.3.0, I don't see any of these examples 
http://urwid.org/examples/index.html

in the urwid directory on my system.
There are many other files but none of the files listed on the URL above

**Comment by wardi** [comment]
The examples are included in this git source repository, but not when installed with pip.

**Comment by ReddyKilowatt** [comment]
Yes, I know. that's a bad idea if you're trying to get someone to know how
to use your software.
Look at all of the examples that come with tinter, wx, qt...

**Comment by wardi** [comment]
I'd certainly consider a pull request that exports these to a pip install as well.
