### ISSUE TITLE
BarGraph with multiple hlines raises WidgetError

### ISSUE THREAD

**Issue by hkoof** [wardi/urwid#66]
Trying to use hlines in a BarGraph, I get this error everytime I try to 
display more than one horizontal line:

urwid.widget.WidgetError: Widget <BarGraph box widget> rendered (116 x 95) canvas when passed size (116, 75)!

Python script to reproduce:

    import urwid

    palette = [
         ('normal', 'dark blue', 'dark gray'),
         ('inverse', 'dark gray', 'dark blue'),
    ]

    def main():
         graph = urwid.BarGraph(
             ['normal', 'inverse'],
             ['normal', 'inverse'],
             { (1,0): 'normal', },
         )
         bardata = [(1,), (2,), (4,), (8,), (16,), (32,)]
         lines = [10]
         graph.set_data(bardata, 40, lines)
         loop = urwid.MainLoop(graph, palette)
         loop.run()

    if __name__ == "__main__":
         main = main()

This works and it shows a line, but when I try to add more lines, e.g.: `lines = [10, 20]` or: `lines = [1,2,5,10]`, then the WidgetError mentioned above is raised.

If I am using hlines the wrong way, I'd like to know what I am doing wrong. But I was told BarGaph should not raise a WidgetError like this anyway. Hence this bug report.

I reproduced this on:
- python 3.4  +  urwid 1.2.1 in a virtualenv
- python 2.7.5  +  urwid 1.1.1 as shipped by ubuntu 13.10.

Best regards,
Heiko Noordhof

**Comment by hkoof** [comment]
This can be closed I think.

**Comment by wardi** [comment]
@hkoof thanks!
