### ISSUE TITLE
MonitoredFocusList does not support negative indices

### ISSUE THREAD

**Issue by cltrudeau** [wardi/urwid#73]
I'm using a Pile which I'm dynamically changing the contents of, I went to remove the last item using a negative index and I get:

`IndexError: focus index is out of range: 2`

Upon digging into the code, it appears there is no accounting for negative indices in the `MonitoredFocusList.__delitem__` call.  It looks like the slicing mechanism used in a bunch of places assumes positive indices. 

I'm using .pop() as a work around, so this isn't a big deal and it may not be worth fixing.  A note in the documentation would be good if this is going to stay as a known issue.

**Comment by hkoof** [comment]
This issue can be closed I think.

**Comment by wardi** [comment]
@hkoof thanks again!
